### ISSUE TITLE
this.userId is not set on server

### ISSUE THREAD

**Issue by sabativi** [idanwe/accounts-password-client-side#3]
Hello,

I am using your package for authentification in an ionic app.
login work fine but when i do :

```
Meteor.publish("examples", function(){
    if (!this.userId)
}
```

`this.userId` is always undefined.

I add account-password on my server.

thanks,

victor

**Comment by idanwe** [comment]
Hey @sabativi, Can you please create a repo with reproducing of the bug?

**Comment by idanwe** [comment]
@sabativi  I'm closing this one due that it is a problem on the server and this package handles the client side only
