### ISSUE TITLE
Create user but do not login afterwards

### ISSUE THREAD

**Issue by mariohmol** [idanwe/accounts-password-client-side#7]
Hi there!

First of all, very nice project, very helpfull!!

I'm trying to make the ionic2 example with accounts-password instead.

https://github.com/mariohmol/ionic2-meteor-messenger

I can install, run , create a user and when i try to login ,always get  `"User not found [403]"`.

Here is the backend where create the user 
- https://github.com/mariohmol/ionic2-meteor-messenger/blob/master/api/server/methods.ts#L88

It appears on mongo db:
- { "_id" : "6SfTARboho9zcBKfv", "createdAt" : ISODate("2016-09-18T18:47:45.203Z"), "services" : { "password" : { "bcrypt" : "$2a$10$fvAWfUOkJ.0lZKrElE4NuOQx
  IYy5joC2WpoF5REXVNPsUG9jMgSk2" } }, "username" : "teste@teste.com", "profile" : {  } }

But cant login afterwards, here is how i'm using on client:
- https://github.com/mariohmol/ionic2-meteor-messenger/blob/master/app/pages/login/login.ts#L46

Any ideias?

thanks!

**Comment by mariohmol** [comment]
I found the error.. my user has just a username as a email..so he does not have a email attribute.

and the selector if checking if has `@` to find by email.. isnt possible to make a equals username OR email?

https://github.com/idanwe/accounts-password-client-side/blob/master/dist/accounts-password-client-side.bundle.js#L1698

**Comment by idanwe** [comment]
@mariohmol, Good to hear that you solved it.

I saw that you had multiple issues about this problem.
Therefor, does the package work for you? Does the issue can be closed?

Regard your question, as far as I know you need to explicit pass object for email or username. Otherwise, pass a string to the method will try to identify the "type" by the existence of `@` [accounts-password code](https://github.com/meteor/meteor/blob/master/packages/accounts-password/password_client.js#L14-L24).

**Comment by mariohmol** [comment]
Yes.. i could made it working using user and email, but if you see this link: 
- https://docs.meteor.com/api/accounts.html#Meteor-loginWithPassword

There for instance says an use email or username:

"user Object or String
Either a string interpreted as a username or an email; or an object with a single key: _email, username or id_. Username or email match in a case insensitive manner"

But if i do that using this module it required to pass both and to be honest thats allright.. tha only suggestion that i would do is about documentation on readme.. someome code snippets in readme and tips like this (must use email and user).. would be great..

**Comment by idanwe** [comment]
@mariohmol it shouldn't be different from what the meteor docs says. Due to it is client side of the **meteor code** just bundled separately. 
So, you don't need to expect for any differences.

**Comment by mariohmol** [comment]
I see.. so maybe there need to be fixed.. but anyway.. if you point your readme to this link https://guide.meteor.com/accounts.html#accounts-password would be good!

 .. and even there i cant find a example using loginWithPassword.. its crazy...

**Comment by idanwe** [comment]
Would you like to make a PR for that?
